[build]
  publish = "public/"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self'; default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://identity.netlify.com https://www.google.com https://www.gstatic.com https://maps.googleapis.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https://csimg.nyc3.cdn.digitaloceanspaces.com https://*.googleapis.com https://*.gstatic.com; connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://maps.googleapis.com https://*.googleapis.com https://identity.netlify.com https://api.netlify.com; frame-src https://www.google.com https://www.gstatic.com https://identity.netlify.com;"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"