backend:
  name: git-gateway
  repo: Callowhill-Web-Designs/winIT
  branch: main
  identity_url: https://auth.decapbridge.com/sites/fe4fac2b-8e78-450a-9428-ecb6313b9db4
  gateway_url: https://gateway.decapbridge.com/

  
local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://callowhillwebdesigns.com/assets/svgs/logo.svg

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
